<?php
$data = array (
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => '主题旅游',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '1',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 0,
    'id' => '2',
    'name' => '主题旅游',
  ),
  22 => 
  array (
    'cat_id' => '22',
    'cat_name' => '当季推荐',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '22',
    'name' => '当季推荐',
  ),
  64 => 
  array (
    'cat_id' => '64',
    'cat_name' => '徒步',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '64',
    'name' => '徒步',
  ),
  65 => 
  array (
    'cat_id' => '65',
    'cat_name' => '体育赛事',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '65',
    'name' => '体育赛事',
  ),
  20 => 
  array (
    'cat_id' => '20',
    'cat_name' => '爸妈游',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '20',
    'name' => '爸妈游',
  ),
  19 => 
  array (
    'cat_id' => '19',
    'cat_name' => '祈福拜佛',
    'measure_unit' => '',
    'parent_id' => '20',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '19',
    'name' => '祈福拜佛',
  ),
  16 => 
  array (
    'cat_id' => '16',
    'cat_name' => '红色之旅',
    'measure_unit' => '',
    'parent_id' => '20',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '16',
    'name' => '红色之旅',
  ),
  17 => 
  array (
    'cat_id' => '17',
    'cat_name' => '亲子游',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '17',
    'name' => '亲子游',
  ),
  73 => 
  array (
    'cat_id' => '73',
    'cat_name' => '海洋公园',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '73',
    'name' => '海洋公园',
  ),
  70 => 
  array (
    'cat_id' => '70',
    'cat_name' => '上海迪士尼',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '70',
    'name' => '上海迪士尼',
  ),
  71 => 
  array (
    'cat_id' => '71',
    'cat_name' => '游乐园',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '71',
    'name' => '游乐园',
  ),
  72 => 
  array (
    'cat_id' => '72',
    'cat_name' => '感受名校',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '72',
    'name' => '感受名校',
  ),
  21 => 
  array (
    'cat_id' => '21',
    'cat_name' => '蜜月游',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '21',
    'name' => '蜜月游',
  ),
  69 => 
  array (
    'cat_id' => '69',
    'cat_name' => '购物血拼',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '69',
    'name' => '购物血拼',
  ),
  68 => 
  array (
    'cat_id' => '68',
    'cat_name' => '浪漫海岛',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '68',
    'name' => '浪漫海岛',
  ),
  18 => 
  array (
    'cat_id' => '18',
    'cat_name' => '户外活动',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '18',
    'name' => '户外活动',
  ),
  76 => 
  array (
    'cat_id' => '76',
    'cat_name' => '滑雪',
    'measure_unit' => '',
    'parent_id' => '18',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '76',
    'name' => '滑雪',
  ),
  77 => 
  array (
    'cat_id' => '77',
    'cat_name' => '潜水',
    'measure_unit' => '',
    'parent_id' => '18',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '77',
    'name' => '潜水',
  ),
  74 => 
  array (
    'cat_id' => '74',
    'cat_name' => '高空项目',
    'measure_unit' => '',
    'parent_id' => '18',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '74',
    'name' => '高空项目',
  ),
  75 => 
  array (
    'cat_id' => '75',
    'cat_name' => '骑行',
    'measure_unit' => '',
    'parent_id' => '18',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '75',
    'name' => '骑行',
  ),
  15 => 
  array (
    'cat_id' => '15',
    'cat_name' => '深度玩法',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '15',
    'name' => '深度玩法',
  ),
  66 => 
  array (
    'cat_id' => '66',
    'cat_name' => '自然探索',
    'measure_unit' => '',
    'parent_id' => '15',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '66',
    'name' => '自然探索',
  ),
  67 => 
  array (
    'cat_id' => '67',
    'cat_name' => '深度摄影',
    'measure_unit' => '',
    'parent_id' => '15',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '67',
    'name' => '深度摄影',
  ),
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '周边旅游',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 0,
    'id' => '1',
    'name' => '周边旅游',
  ),
  29 => 
  array (
    'cat_id' => '29',
    'cat_name' => '特色主题',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '29',
    'name' => '特色主题',
  ),
  82 => 
  array (
    'cat_id' => '82',
    'cat_name' => '温泉',
    'measure_unit' => '',
    'parent_id' => '29',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '82',
    'name' => '温泉',
  ),
  81 => 
  array (
    'cat_id' => '81',
    'cat_name' => '看大熊猫',
    'measure_unit' => '',
    'parent_id' => '29',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '81',
    'name' => '看大熊猫',
  ),
  26 => 
  array (
    'cat_id' => '26',
    'cat_name' => '热门景点',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '26',
    'name' => '热门景点',
  ),
  27 => 
  array (
    'cat_id' => '27',
    'cat_name' => '九寨沟',
    'measure_unit' => '',
    'parent_id' => '26',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '27',
    'name' => '九寨沟',
  ),
  24 => 
  array (
    'cat_id' => '24',
    'cat_name' => '周边目的地',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '24',
    'name' => '周边目的地',
  ),
  79 => 
  array (
    'cat_id' => '79',
    'cat_name' => '成都',
    'measure_unit' => '',
    'parent_id' => '24',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '79',
    'name' => '成都',
  ),
  80 => 
  array (
    'cat_id' => '80',
    'cat_name' => '雅安',
    'measure_unit' => '',
    'parent_id' => '24',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '80',
    'name' => '雅安',
  ),
  28 => 
  array (
    'cat_id' => '28',
    'cat_name' => '交通方式',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '28',
    'name' => '交通方式',
  ),
  85 => 
  array (
    'cat_id' => '85',
    'cat_name' => '飞机游',
    'measure_unit' => '',
    'parent_id' => '28',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '85',
    'name' => '飞机游',
  ),
  23 => 
  array (
    'cat_id' => '23',
    'cat_name' => '火车游',
    'measure_unit' => '',
    'parent_id' => '28',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '23',
    'name' => '火车游',
  ),
  78 => 
  array (
    'cat_id' => '78',
    'cat_name' => '巴士游',
    'measure_unit' => '',
    'parent_id' => '28',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '78',
    'name' => '巴士游',
  ),
  25 => 
  array (
    'cat_id' => '25',
    'cat_name' => '游玩天数',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '25',
    'name' => '游玩天数',
  ),
  83 => 
  array (
    'cat_id' => '83',
    'cat_name' => '一天游',
    'measure_unit' => '',
    'parent_id' => '25',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '83',
    'name' => '一天游',
  ),
  84 => 
  array (
    'cat_id' => '84',
    'cat_name' => '两天游',
    'measure_unit' => '',
    'parent_id' => '25',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '84',
    'name' => '两天游',
  ),
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => '西部旅游',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '8',
    'goods_num' => 0,
    'level' => 0,
    'id' => '5',
    'name' => '西部旅游',
  ),
  35 => 
  array (
    'cat_id' => '35',
    'cat_name' => '广西',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '35',
    'name' => '广西',
  ),
  89 => 
  array (
    'cat_id' => '89',
    'cat_name' => '桂林',
    'measure_unit' => '',
    'parent_id' => '35',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '89',
    'name' => '桂林',
  ),
  32 => 
  array (
    'cat_id' => '32',
    'cat_name' => '甘肃',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '32',
    'name' => '甘肃',
  ),
  94 => 
  array (
    'cat_id' => '94',
    'cat_name' => '莫高窟',
    'measure_unit' => '',
    'parent_id' => '32',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '94',
    'name' => '莫高窟',
  ),
  92 => 
  array (
    'cat_id' => '92',
    'cat_name' => '陕西',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '92',
    'name' => '陕西',
  ),
  86 => 
  array (
    'cat_id' => '86',
    'cat_name' => '兵马俑',
    'measure_unit' => '',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '86',
    'name' => '兵马俑',
  ),
  33 => 
  array (
    'cat_id' => '33',
    'cat_name' => '贵州',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '33',
    'name' => '贵州',
  ),
  87 => 
  array (
    'cat_id' => '87',
    'cat_name' => '黄果树瀑布',
    'measure_unit' => '',
    'parent_id' => '33',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '87',
    'name' => '黄果树瀑布',
  ),
  30 => 
  array (
    'cat_id' => '30',
    'cat_name' => '云南',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '30',
    'name' => '云南',
  ),
  90 => 
  array (
    'cat_id' => '90',
    'cat_name' => '西双版纳',
    'measure_unit' => '',
    'parent_id' => '30',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '90',
    'name' => '西双版纳',
  ),
  34 => 
  array (
    'cat_id' => '34',
    'cat_name' => '四川',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '34',
    'name' => '四川',
  ),
  91 => 
  array (
    'cat_id' => '91',
    'cat_name' => '九寨沟',
    'measure_unit' => '',
    'parent_id' => '34',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '91',
    'name' => '九寨沟',
  ),
  31 => 
  array (
    'cat_id' => '31',
    'cat_name' => '西藏',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '31',
    'name' => '西藏',
  ),
  93 => 
  array (
    'cat_id' => '93',
    'cat_name' => '布达拉宫',
    'measure_unit' => '',
    'parent_id' => '31',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '93',
    'name' => '布达拉宫',
  ),
  88 => 
  array (
    'cat_id' => '88',
    'cat_name' => '新疆',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '88',
    'name' => '新疆',
  ),
  95 => 
  array (
    'cat_id' => '95',
    'cat_name' => '天山',
    'measure_unit' => '',
    'parent_id' => '88',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '95',
    'name' => '天山',
  ),
  11 => 
  array (
    'cat_id' => '11',
    'cat_name' => '国内其他',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '5',
    'goods_num' => '6',
    'level' => 0,
    'id' => '11',
    'name' => '国内其他',
  ),
  44 => 
  array (
    'cat_id' => '44',
    'cat_name' => '东北',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '44',
    'name' => '东北',
  ),
  105 => 
  array (
    'cat_id' => '105',
    'cat_name' => '金石滩',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '105',
    'name' => '金石滩',
  ),
  106 => 
  array (
    'cat_id' => '106',
    'cat_name' => '五大连地',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '106',
    'name' => '五大连地',
  ),
  107 => 
  array (
    'cat_id' => '107',
    'cat_name' => '长白山',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '107',
    'name' => '长白山',
  ),
  41 => 
  array (
    'cat_id' => '41',
    'cat_name' => '海南',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '41',
    'name' => '海南',
  ),
  96 => 
  array (
    'cat_id' => '96',
    'cat_name' => '三亚',
    'measure_unit' => '',
    'parent_id' => '41',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '96',
    'name' => '三亚',
  ),
  42 => 
  array (
    'cat_id' => '42',
    'cat_name' => '河南',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '42',
    'name' => '河南',
  ),
  101 => 
  array (
    'cat_id' => '101',
    'cat_name' => '龙门石窟',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '101',
    'name' => '龙门石窟',
  ),
  99 => 
  array (
    'cat_id' => '99',
    'cat_name' => '少林寺',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '99',
    'name' => '少林寺',
  ),
  100 => 
  array (
    'cat_id' => '100',
    'cat_name' => '洛阳',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '100',
    'name' => '洛阳',
  ),
  97 => 
  array (
    'cat_id' => '97',
    'cat_name' => '湖南',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '97',
    'name' => '湖南',
  ),
  98 => 
  array (
    'cat_id' => '98',
    'cat_name' => '天门山',
    'measure_unit' => '',
    'parent_id' => '97',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '98',
    'name' => '天门山',
  ),
  43 => 
  array (
    'cat_id' => '43',
    'cat_name' => '华东',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '43',
    'name' => '华东',
  ),
  102 => 
  array (
    'cat_id' => '102',
    'cat_name' => '周庄',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '102',
    'name' => '周庄',
  ),
  103 => 
  array (
    'cat_id' => '103',
    'cat_name' => '西湖',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '103',
    'name' => '西湖',
  ),
  104 => 
  array (
    'cat_id' => '104',
    'cat_name' => '普陀山',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '104',
    'name' => '普陀山',
  ),
  9 => 
  array (
    'cat_id' => '9',
    'cat_name' => '香港澳门',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '9',
    'name' => '香港澳门',
  ),
  40 => 
  array (
    'cat_id' => '40',
    'cat_name' => '热门目的地',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '40',
    'name' => '热门目的地',
  ),
  125 => 
  array (
    'cat_id' => '125',
    'cat_name' => '香港一地',
    'measure_unit' => '',
    'parent_id' => '40',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '125',
    'name' => '香港一地',
  ),
  128 => 
  array (
    'cat_id' => '128',
    'cat_name' => '港澳连游',
    'measure_unit' => '',
    'parent_id' => '40',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 2,
    'id' => '128',
    'name' => '港澳连游',
  ),
  129 => 
  array (
    'cat_id' => '129',
    'cat_name' => '澳门一地',
    'measure_unit' => '',
    'parent_id' => '40',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '129',
    'name' => '澳门一地',
  ),
  36 => 
  array (
    'cat_id' => '36',
    'cat_name' => '热门景点',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '36',
    'name' => '热门景点',
  ),
  109 => 
  array (
    'cat_id' => '109',
    'cat_name' => '澳门大三巴牌坊',
    'measure_unit' => '',
    'parent_id' => '36',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '109',
    'name' => '澳门大三巴牌坊',
  ),
  110 => 
  array (
    'cat_id' => '110',
    'cat_name' => '香港海洋公园',
    'measure_unit' => '',
    'parent_id' => '36',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '110',
    'name' => '香港海洋公园',
  ),
  112 => 
  array (
    'cat_id' => '112',
    'cat_name' => '香港迪士尼乐园',
    'measure_unit' => '',
    'parent_id' => '36',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '112',
    'name' => '香港迪士尼乐园',
  ),
  39 => 
  array (
    'cat_id' => '39',
    'cat_name' => '游玩方式',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '39',
    'name' => '游玩方式',
  ),
  122 => 
  array (
    'cat_id' => '122',
    'cat_name' => '跟团游',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '122',
    'name' => '跟团游',
  ),
  123 => 
  array (
    'cat_id' => '123',
    'cat_name' => '半自助',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '123',
    'name' => '半自助',
  ),
  124 => 
  array (
    'cat_id' => '124',
    'cat_name' => '自由行',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '124',
    'name' => '自由行',
  ),
  12 => 
  array (
    'cat_id' => '12',
    'cat_name' => '台湾地区',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '3',
    'goods_num' => '6',
    'level' => 0,
    'id' => '12',
    'name' => '台湾地区',
  ),
  49 => 
  array (
    'cat_id' => '49',
    'cat_name' => '热门玩法',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '49',
    'name' => '热门玩法',
  ),
  132 => 
  array (
    'cat_id' => '132',
    'cat_name' => '台北+高雄+垦丁',
    'measure_unit' => '',
    'parent_id' => '49',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '132',
    'name' => '台北+高雄+垦丁',
  ),
  45 => 
  array (
    'cat_id' => '45',
    'cat_name' => '热门目的地',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '45',
    'name' => '热门目的地',
  ),
  130 => 
  array (
    'cat_id' => '130',
    'cat_name' => '台北',
    'measure_unit' => '',
    'parent_id' => '45',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '130',
    'name' => '台北',
  ),
  48 => 
  array (
    'cat_id' => '48',
    'cat_name' => '热门景点',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '48',
    'name' => '热门景点',
  ),
  131 => 
  array (
    'cat_id' => '131',
    'cat_name' => '台北故宫',
    'measure_unit' => '',
    'parent_id' => '48',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '131',
    'name' => '台北故宫',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => '旅游攻略',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '6',
    'name' => '旅游攻略',
  ),
  133 => 
  array (
    'cat_id' => '133',
    'cat_name' => '出境游路线推荐',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '133',
    'name' => '出境游路线推荐',
  ),
  143 => 
  array (
    'cat_id' => '143',
    'cat_name' => '台湾 + 香港',
    'measure_unit' => '',
    'parent_id' => '133',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '143',
    'name' => '台湾 + 香港',
  ),
  141 => 
  array (
    'cat_id' => '141',
    'cat_name' => '香港 + 澳门',
    'measure_unit' => '',
    'parent_id' => '133',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '141',
    'name' => '香港 + 澳门',
  ),
  142 => 
  array (
    'cat_id' => '142',
    'cat_name' => '台北 + 台中 + 嘉义 + 高雄 +',
    'measure_unit' => '',
    'parent_id' => '133',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '142',
    'name' => '台北 + 台中 + 嘉义 + 高雄 +',
  ),
  134 => 
  array (
    'cat_id' => '134',
    'cat_name' => '国内胜地路线推荐',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 1,
    'id' => '134',
    'name' => '国内胜地路线推荐',
  ),
  140 => 
  array (
    'cat_id' => '140',
    'cat_name' => '长沙 + 张家界 + 天门山 + 湘西',
    'measure_unit' => '',
    'parent_id' => '134',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '140',
    'name' => '长沙 + 张家界 + 天门山 + 湘西',
  ),
  137 => 
  array (
    'cat_id' => '137',
    'cat_name' => '贵州西江千户苗寨 - 黄果树瀑布 - 凯',
    'measure_unit' => '',
    'parent_id' => '134',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '137',
    'name' => '贵州西江千户苗寨 - 黄果树瀑布 - 凯',
  ),
  138 => 
  array (
    'cat_id' => '138',
    'cat_name' => '云南昆明 + 普洱 + 西双版纳 + 野',
    'measure_unit' => '',
    'parent_id' => '134',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '138',
    'name' => '云南昆明 + 普洱 + 西双版纳 + 野',
  ),
  135 => 
  array (
    'cat_id' => '135',
    'cat_name' => '兰州 + 敦煌 + 嘉峪关 + 张掖 +',
    'measure_unit' => '',
    'parent_id' => '134',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '135',
    'name' => '兰州 + 敦煌 + 嘉峪关 + 张掖 +',
  ),
  139 => 
  array (
    'cat_id' => '139',
    'cat_name' => '华东 - 黄山 - 千岛湖 - 周庄',
    'measure_unit' => '',
    'parent_id' => '134',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '139',
    'name' => '华东 - 黄山 - 千岛湖 - 周庄',
  ),
  136 => 
  array (
    'cat_id' => '136',
    'cat_name' => '广西桂林 + 阳朔 + 漓江',
    'measure_unit' => '',
    'parent_id' => '134',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '136',
    'name' => '广西桂林 + 阳朔 + 漓江',
  ),
);
?>